name: fintech_frontend
description: Flutter frontend for RBAC FinTech backend
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & routing
  google_fonts: ^5.0.0
  go_router: ^7.0.0
  flutter_riverpod: ^2.0.0

  # Networking & storage
  dio: ^5.0.0
  flutter_secure_storage: ^8.0.0

  # Utilities
  intl: ^0.18.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

uses-material-design: true